---
- name: install the puppet repo rpm from a remote repo
  yum:
    name: https://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm
    state: present

- name: Ensure Puppet Server is installed.
  yum:
    name: puppet-server
    state: installed

- name: Ensure hostname is ready
  lineinfile:
    dest: /etc/hosts
    line: "{{ ansible_ssh_host }} {{ inventory_hostname }}"

- name: Ensure Puppet configuration is ready
  template:
    src: puppet.conf.j2
    dest: /etc/puppet/puppet.conf
  notify:
    - restart puppet master

- name: Ensure Puppet Master is up
  service:
    name: puppetmaster
    state: started
