---

- name: Puppet Agent setup
  hosts: puppet-agent
  roles:
    #- libselinux-python # TODO check if it is neccessary for prod
    - puppet-agent
  # TODO become depends on env vars
  become: true
