---

es_host: ElasticSearch01.xxxxcf.com
es_host_2: ElasticSearch02.xxxxcf.com
es_host_3: ElasticSearch03.xxxxcf.com
es_port: 9200
es_cluster:
  - "{{ es_host }}:{{ es_port }}"
  - "{{ es_host_2 }}:{{ es_port }}"
  - "{{ es_host_3 }}:{{ es_port }}"

kibana_host: KibanaDockers.xxxxcf.com
kibana_port: 5601

logstash_getway: Logstash-POS.xxxxcf.com
logstash_getway_port: 5044

zookeeper: ZooKeeper.xxxxcf.com:2181
