---

kafka_topic: syslog
es_index: syslog

logstash_filters: |
  grok {
    match => {
      "message" => "%{SYSLOGTIMESTAMP:timestamp} (?:%{SYSLOGFACILITY} )?%{SYSLOGHOST:logsource} %{SYSLOGPROG}"
    }
  }
  date {
    match => [ "timestamp" , "MMM dd HH:mm:ss","MMM  dd HH:mm:ss" ]
    timezone => "Asia/Shanghai"
    target => "@timestamp"
  }

logstash_outputs: |
  elasticsearch {
    hosts => ["{{ es_cluster | join('", "') }}"]
    index => "{{ es_index }}-%{+YYYY.MM.dd}"
    document_type => "%{type}"
  }
