---
- name: Ensure Puppet Server is installed.
  yum:
    name: puppet
    state: installed

- name: Ensure hostname is ready
  lineinfile:
    dest: /etc/hosts
    line: "{{ ansible_ssh_host }} {{ inventory_hostname }}"

- name: Ensure puppet master hostname is ready
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[groups['puppet-server'][0]]['ansible_ssh_host'] }} {{ hostvars[groups['puppet-server'][0]]['inventory_hostname'] }}"

- name: Ensure Puppet configuration is ready
  template:
    src: puppet.conf.j2
    dest: /etc/puppet/puppet.conf
  notify:
    - restart puppet

- name: Ensure Puppet Agent is up
  service:
    name: puppet
    state: started
