---

- name: Ensure app dir is created
  file: path={{ item.dir }} state=directory
  with_items: "{{ app_configs }}"

- name: Ensure profile vars are replaced in app config file
  template: src={{ item.name }}.j2 dest={{ item.dir }}/{{ item.name }}
  with_items: "{{ app_configs }}"
