---

es_heap_size: "16g"

es_config: {
  network.host: "0.0.0.0",
  node.name: "swa-es-1",
  cluster.name: "elasticsearch_cluster_prod",
  discovery.zen.ping.unicast.hosts: ["127.0.0.1", "{{ es_host_2 }}", "{{ es_host_3 }}"],
  http.port: 9200,
  transport.tcp.port: 9300,
  node.data: true,
  node.master: true,
  bootstrap.mlockall: true,
  discovery.zen.ping.multicast.enabled: false,
  indices.fielddata.cache.size: 70%,
  index.number_of_shards: 3
}

es_plugins:
  - plugin: lmenezes/elasticsearch-kopf
    version: v2.1.1
