---

docker_compose_dir: /opt/logstash/indexer/journals/1
app_configs:
  - { dir: /opt/logstash/indexer/journals/1, name: indexer.conf }
  - { dir: /opt/logstash/indexer/patterns, name: common-pattern }

container_name: indexer-pos-journals-1
