---
elasticsearch_curator_cron_jobs:
  - {
    name: "Delete old elasticsearch indices.",
    job: "/usr/bin/curator --host {{ es_host }} --port {{ es_port }} --logfile /var/log/curator delete indices --older-than 90 --time-unit days --timestring '\\%Y.\\%m.\\%d'",
    minute: 0,
    hour: 1
  }
  - {
    name: "Close old elasticsearch indices.",
    job: "/usr/bin/curator --host {{ es_host }} --port {{ es_port }} --logfile /var/log/curator close indices --older-than 30 --time-unit days --timestring '\\%Y.\\%m.\\%d'",
    minute: 0,
    hour: 1
  }
