---

docker_compose_dir: /opt/logstash/indexer/syslog/1
app_configs:
  - { dir: /opt/logstash/indexer/syslog/1, name: indexer.conf }

container_name: indexer-pos-syslog-1

logstash_inputs: |
  kafka {
    consumer_id => "syslog-01"
    group_id => "syslog"
    topic_id => "{{ kafka_topic }}"
    zk_connect => "{{ zookeeper }}"
  }
